#!/usr/bin/env sh

appledoc --project-name SVNetworking \
         --project-company eBay \
         --company-id com.ebay \
         --create-html \
         --no-create-docset \
         --keep-undocumented-objects \
         --keep-undocumented-members \
         --no-repeat-first-par \
         --no-merge-categories \
         -o $(dirname $0) \
         $(dirname $0)/../SVNetworking/SVNetworking/*.h
